steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'verify']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'scala-app1', '--trigger-http', '--memory', '2048MB' ,'--service-account', 'scala-app@learning-265808.iam.gserviceaccount.com', '--runtime', 'java11', '--entry-point', 'com.ryansusana.scala.Main', '--allow-unauthenticated']